
#include "decalaration/bitwise.h"
#include "decalaration/divisible.h"
#include "decalaration/even_odd.h"
#include "decalaration/largest2.h"
#include "decalaration/largest3.h"
#include "decalaration/month.h"
#include "decalaration/month1.h"
#include "decalaration/pos_neg.h"
#include "decalaration/profit_loss.h"
#include "decalaration/radius.h"
#include "decalaration/vowel.h"